# Generated by Django 5.1.3 on 2024-11-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='account',
            new_name='account_no',
        ),
        migrations.AddField(
            model_name='profile',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
    ]
